name: Billing schedular workflow

on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '48 12 * * *'

jobs:
  billing_job:
    steps:
      - name: Execute initiate billing service
        run: bash scripts/initiate-billing.sh
